---
title: "Presentation with Plotly"
author: "A Kannankeril"
date: "3/1/2021"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```


```{r libraries, echo=FALSE}
library(tidyverse)
library(plotly)
library(RColorBrewer)
mycolors<-colorRampPalette(brewer.pal(8, "Set2"))(18)
world_univ<-read.csv("timesData.csv",header = T,sep = ",")
top_hundred<- world_univ %>%
            mutate(ranking=as.numeric(gsub("=", "", as.character(world_rank))))

top_univ<-top_hundred %>%
      filter(ranking<=100) %>%
      arrange(year,ranking)
```
## Plotly graph code
Below is the plotly code for scatter graph for top 100 universities that shows the number of citations and their rankings. [World Universities Data](https://www.kaggle.com/mylesoneill/world-university-rankings?select=timesData.csv)

```{r code, eval=FALSE}
fig <- top_univ %>%
      plot_ly(y = ~citations, x = ~ranking,
              text=~university_name, hoverinfo="text") %>%
            add_markers(color = ~country, 
                        colors=mycolors,frame = ~year)
fig
```
Use the right arrow to view the next slide.

## Citations vs. Ranking 
Slide or Play to see top universities over the years for each country listed. Hover over the data points to see the university.


```{r plot,echo=FALSE,fig.height=4}
fig <- top_univ %>%
      plot_ly(y = ~citations, x = ~ranking,
              text=~university_name, hoverinfo="text") %>%
            add_markers(color = ~country, 
                        colors=mycolors,frame = ~year)
fig
```

